### PR TITLE
Make positions unique

### LINKED ISSUE #22: Bug: Source produces records with the same position
### Bug description

Conduit requires record positions to be unique (at least records that are produced in a short time frame). The Kafka source produces records that all contain the same position (the group id), see [this line](https://github.com/ConduitIO/conduit-connector-kafka/blob/10179858b4af7e8f470e18c30e5d57027acb7f46/consumer.go#L146) (second return param is supposed to be the position).

This causes Conduit to throw this error:
```
2022-04-06T14:01:07+00:00 ERR encountered two records with the same position and can't differentiate them (could be that you are using a pipeline with two same source connectors and they both produced a record with the same position at the same time, could also be a badly written source connector that doesn't assign unique positions to records) component=AckerNode message_id=f8ce7c83-c0ed-4826-bc9b-8ebb2d533efb/e50b35f9-c9e0-41b7-b740-43b271107daf node_id=6967a6f8-032e-4f65-bc1a-711b1ce254a9-acker pipeline_id=d8b9a605-627e-42f0-b4e0-acaea8feaaa7
```

### Steps to reproduce

1. Create a pipeline with a Kafka source
2. Create the source topic and write multiple messages in it
3. Start pipeline
4. It produces records with the same position and pipeline stops

### Version

v0.1.0

### PR DESCRIPTION
**Pull request by hariso**
### Description

Fixes #22 

### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit-connector-kafka/pulls) for the same update/change.
- [x] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: source.go [hunk 1]
```diff
@@ -46,13 +46,14 @@ func (s *Source) Configure(ctx context.Context, cfg map[string]string) error {
 }
 
 func (s *Source) Open(ctx context.Context, pos sdk.Position) error {
+	sdk.Logger(ctx).Info().Bytes("position", pos).Msg("Opening a source...")
```
Comment (lovromazgon) [inline source.go:49]: We expect the position to be a JSON string, right? It would be more valuable to display it as a string then.
```suggestion
	sdk.Logger(ctx).Info().Str("position", string(pos)).Msg("Opening a source...")
```

File: source.go [hunk 2]
```diff
@@ -46,13 +46,14 @@ func (s *Source) Configure(ctx context.Context, cfg map[string]string) error {
...
 	if err != nil {
 		return fmt.Errorf("failed to create Kafka client: %w", err)
 	}
 	s.Consumer = client
 
-	err = s.startFrom(pos)
+	err = s.startFrom(ctx, pos)
 	if err != nil {
 		return fmt.Errorf("couldn't start from position: %w", err)
 	}
```
Comment (lovromazgon) [inline source.go:59]: Now that I think about it, we don't have a need to store `lastPositionRead` anymore, we can remove it completely and just call `s.Consumer.StartFrom` directly from here.
```suggestion
	err = s.Consumer.StartFrom(s.Config, string(pos))
	if err != nil {
		return fmt.Errorf("couldn't start from position %v: %w", string(pos), err)
	}
```

File: consumer_test.go [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+
+import (
+	"encoding/json"
+	"testing"
+
+	"github.com/matryer/is"
+	"github.com/segmentio/kafka-go"
+)
+
+func TestMessagePosition(t *testing.T) {
```
Comment (lovromazgon) [inline consumer_test.go:25]: We already have the file `segment_reader_test.go`, we should either move this test there or move the others here (I would prefer the latter because it's customary to have `foo.go` and `foo_test.go`).

**Review by lovromazgon — CHANGES_REQUESTED** [review]
Watch out, the consumer won't be able to correctly start from the last position now, it still expects that the position is a groupID ([this function](https://github.com/ConduitIO/conduit-connector-kafka/blob/4d473cd98b0f79b58e77e8fbca4cd30af21484df/consumer.go#L76)).

File: source.go (hunk 1 above)
Comment (hariso) [reply source.go:49]: > We expect the position to be a JSON string, right?

At this point, yes.

File: consumer_test.go (hunk 3 above)
Comment (hariso) [reply consumer_test.go:25]: Makes sense. This is a leftover from when newReader() was a function and not a method on the consumer.

**Comment by hariso** [comment]
> Watch out, the consumer won't be able to correctly start from the last position now, it still expects that the position is a groupID ([this function](https://github.com/ConduitIO/conduit-connector-kafka/blob/4d473cd98b0f79b58e77e8fbca4cd30af21484df/consumer.go#L76)).

Good point. I was just about to go through a test plan manually.

File: source.go (hunk 1 above)
Comment (hariso) [reply source.go:48]: I did pay attention to this, so I checked the logs and saw that it was actually already "stringified". Then I checked the docs, and they actually confirm its adding the bytes as a string.

Comment (lovromazgon) [reply source.go:48]: TIL!

**Review by lovromazgon — COMMENTED** [review]
Functionally looks good, I'd like us to clean up the code a bit before merging. You know, _leave the campground cleaner than you found it_.

File: consumer_integration_test.go [hunk 4]
```diff
@@ -121,11 +120,11 @@ func waitForMessage(consumer kafka.Consumer, timeout time.Duration) (*skafka.Mes
 	case r := <-c:
 		return r.msg, r.pos, r.err // completed normally
 	case <-time.After(timeout):
-		return nil, "", errors.New("timed out while waiting for message") // timed out
+		return nil, nil, errors.New("timed out while waiting for message") // timed out
 	}
 }
 
-func sendTestMessages(t *testing.T, cfg kafka.Config, from int, to int) {
+func sendTestMessages(t *testing.T, cfg Config, from int, to int) {
```
[the remark this answers is not in the document]
Comment (hariso) [reply consumer_integration_test.go:127]: That's interesting, I moved sendTestMessage, but not sendTestMessages.

File: source.go [hunk 5]
```diff
@@ -46,53 +45,40 @@ func (s *Source) Configure(ctx context.Context, cfg map[string]string) error {
...
-	// The check is in place, to avoid reconstructing the Kafka consumer.
-	if s.lastPositionRead != nil && bytes.Equal(s.lastPositionRead, position) {
-		return nil
-	}
-
-	err := s.Consumer.StartFrom(s.Config, string(position))
-	if err != nil {
-		return fmt.Errorf("couldn't start from given position %v due to %w", string(position), err)
-	}
-	s.lastPositionRead = position
```
[the remark this answers is not in the document]
Comment (hariso) [reply source.go:89]: :+1:

File: test_common.go [hunk 6]
```diff
@@ -26,3 +31,43 @@ func readFile(filename string, t *testing.T) string {
...
+	return writer.WriteMessages(
+		context.Background(),
+		skafka.Message{
+			Key:   []byte(key),
+			Value: []byte(payload),
+		},
+	)
+}
+
+func testConfig() Config {
```
[the remark this answers is not in the document]
Comment (hariso) [reply test_common.go:62]: Yeah, it's since some tests are in the kafka package and others in kafka_test. I planned working on tests a bit more, so I'll be cleaning up some things too. Thanks for raising this to my attention!

File: destination_integration_test.go [hunk 7]
```diff
@@ -12,15 +12,14 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-package kafka_test
+package kafka
```
[the remark this answers is not in the document]
Comment (hariso) [reply destination_integration_test.go:15]: Yeah, I wanted to do some of the others too, but couldn't because of cyclic imports due to the mocks, so I thought I shouldn't spend time on it now.

File: test_common.go [hunk 8]
```diff
@@ -15,8 +15,13 @@
 package kafka
 
 import (
+	"context"
```
[the remark this answers is not in the document]
Comment (hariso) [reply test_common.go:18]: Good point. :+1:

**Review by lovromazgon — APPROVED** [review]
