### PR TITLE
Fix: Source ack commits unprocessed messages

### LINKED ISSUE #23: Bug: Source ack commits unprocessed messages
### Bug description

[`segmentConsumer.Ack`](https://github.com/ConduitIO/conduit-connector-kafka/blob/10179858b4af7e8f470e18c30e5d57027acb7f46/consumer.go#L150) always commits the last seen message. The issue is that Conduit can process multiple messages at the same time, so the consumer could be acking a message that hasn't been fully processed on the destination yet. This also means that restarting a pipeline at the same place it left off isn't guaranteed with the current behavior.

### Steps to reproduce

1. Read 5 messages from source
2. Ack only 1 message
3. Stop and start source again
4. 4 messages will be lost

### Version

v0.1.0

### PR DESCRIPTION
**Pull request by hariso**
### Description

Fixes #23 

### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit-connector-kafka/pulls) for the same update/change.
- [x] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: consumer.go [hunk 1]
```diff
@@ -75,8 +77,10 @@ func parsePosition(bytes []byte) (position, error) {
 }
 
 type segmentConsumer struct {
-	reader      *kafka.Reader
-	lastMsgRead *kafka.Message
+	reader *kafka.Reader
+	// unackMessages represents all messages which have been read but not acknowledged.
+	// They are ordered in the way they were read.
+	unackMessages []*kafka.Message
```
Comment (hariso) [inline consumer.go:83]: It might make sense to limit the capacity of this slice, to prevent memory leaks when, for example, a message is "stuck".

File: consumer.go [hunk 2]
```diff
@@ -181,7 +185,7 @@ func (c *segmentConsumer) Get(ctx context.Context) (*kafka.Message, []byte, erro
 		return nil, nil, fmt.Errorf("couldn't get message's position: %w", err)
 	}
 
-	c.lastMsgRead = &msg
+	c.unackMessages = append(c.unackMessages, &msg)
```
Comment (lovromazgon) [inline consumer.go:188]: We are appending messages here (happens in one goroutine) ...

File: consumer.go [hunk 3]
```diff
@@ -195,15 +199,36 @@ func (c *segmentConsumer) positionOf(m *kafka.Message) ([]byte, error) {
...
+	err := c.canAck(position)
+	if err != nil {
+		return fmt.Errorf("ack not possible: %w", err)
+	}
+	err = c.reader.CommitMessages(context.Background(), *c.unackMessages[0])
 	if err != nil {
 		return fmt.Errorf("couldn't commit messages: %w", err)
 	}
+	// remove the message from slice of unacknowledged messages
+	c.unackMessages = c.unackMessages[1:]
```
Comment (lovromazgon) [inline consumer.go:212]: ... and we are reading and removing messages here (another goroutine). We need to set up a lock to make sure we don't run into race conditions.

File: consumer.go [hunk 4]
```diff
@@ -195,15 +199,36 @@ func (c *segmentConsumer) positionOf(m *kafka.Message) ([]byte, error) {
...
+	if len(c.unackMessages) == 0 {
+		return fmt.Errorf("requested ack for %q but no unacknowledged messages found", position)
+	}
+	pos, err := c.positionOf(c.unackMessages[0])
+	if err != nil {
+		return fmt.Errorf("failed to get position of first unacknowledged message: %w", err)
+	}
+	// We're going to yell at Conduit for not keeping its promise:
+	// acks should be requested in the same order reads were done.
+	if bytes.Compare(pos, position) != 0 {
```
Comment (lovromazgon) [inline consumer.go:226]: Depending on how we solve nacks, this might not always be the expected behavior. Let's talk about this synchronously, since it's a bit complicated to fit into a PR comment, also this PR is not the correct place to have the debate.

File: consumer.go (hunk 3 above)
Comment (hariso) [reply consumer.go:220]: Good point with that. I've added that in [b38c192](https://github.com/ConduitIO/conduit-connector-kafka/pull/30/commits/b38c19232c7151199c21a737945802014ad3cd29).

File: consumer.go (hunk 4 above)
Comment (lovromazgon) [reply consumer.go:234]: We decided to implement a guarantee in Conduit that will ensure acknowledgments are sent in the correct order and won't be skipped. This code should work fine once we add that.

File: consumer.go (hunk 3 above)
Comment (lovromazgon) [reply consumer.go:220]: That should do the trick!

**Review by lovromazgon — APPROVED** [review]
